[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  branch = "master"

[[constraint]]
  name = "github.com/auth0/go-jwt-middleware"
  branch = "master"